if("${BUILD_STEP}" STREQUAL "patch")
    message("BUILD_STEP: patch")
    execute_process(COMMAND git apply --check -R "${PATCH_FILE}" RESULT_VARIABLE ret)
    if(NOT ret EQUAL "0")
        execute_process(COMMAND git apply "${PATCH_FILE}")
    endif()
endif()
