#include-once
#include "dlib_interface.au3"

; keyboard_state_masks
Global Const $DLIB_IMAGE_WINDOW_KBD_MOD_NONE = 0
Global Const $DLIB_IMAGE_WINDOW_KBD_MOD_SHIFT = 1
Global Const $DLIB_IMAGE_WINDOW_KBD_MOD_CONTROL = 2
Global Const $DLIB_IMAGE_WINDOW_KBD_MOD_ALT = 4
Global Const $DLIB_IMAGE_WINDOW_KBD_MOD_META = 8
Global Const $DLIB_IMAGE_WINDOW_KBD_MOD_CAPS_LOCK = 16
Global Const $DLIB_IMAGE_WINDOW_KBD_MOD_NUM_LOCK = 32
Global Const $DLIB_IMAGE_WINDOW_KBD_MOD_SCROLL_LOCK = 64

; non_printable_keyboard_keys
Global Const $DLIB_IMAGE_WINDOW_KEY_BACKSPACE = "BACKSPACE"
Global Const $DLIB_IMAGE_WINDOW_KEY_SHIFT = "SHIFT"
Global Const $DLIB_IMAGE_WINDOW_KEY_CTRL = "CTRL"
Global Const $DLIB_IMAGE_WINDOW_KEY_ALT = "ALT"
Global Const $DLIB_IMAGE_WINDOW_KEY_PAUSE = "PAUSE"
Global Const $DLIB_IMAGE_WINDOW_KEY_CAPS_LOCK = "CAPS_LOCK"
Global Const $DLIB_IMAGE_WINDOW_KEY_ESC = "ESC"
Global Const $DLIB_IMAGE_WINDOW_KEY_PAGE_UP = "PAGE_UP"
Global Const $DLIB_IMAGE_WINDOW_KEY_PAGE_DOWN = "PAGE_DOWN"
Global Const $DLIB_IMAGE_WINDOW_KEY_END = "END"
Global Const $DLIB_IMAGE_WINDOW_KEY_HOME = "HOME"
Global Const $DLIB_IMAGE_WINDOW_KEY_LEFT = "LEFT"
Global Const $DLIB_IMAGE_WINDOW_KEY_RIGHT = "RIGHT"
Global Const $DLIB_IMAGE_WINDOW_KEY_UP = "UP"
Global Const $DLIB_IMAGE_WINDOW_KEY_DOWN = "DOWN"
Global Const $DLIB_IMAGE_WINDOW_KEY_INSERT = "INSERT"
Global Const $DLIB_IMAGE_WINDOW_KEY_DELETE = "DELETE"
Global Const $DLIB_IMAGE_WINDOW_KEY_SCROLL_LOCK = "SCROLL_LOCK"
Global Const $DLIB_IMAGE_WINDOW_KEY_F1 = "F1"
Global Const $DLIB_IMAGE_WINDOW_KEY_F2 = "F2"
Global Const $DLIB_IMAGE_WINDOW_KEY_F3 = "F3"
Global Const $DLIB_IMAGE_WINDOW_KEY_F4 = "F4"
Global Const $DLIB_IMAGE_WINDOW_KEY_F5 = "F5"
Global Const $DLIB_IMAGE_WINDOW_KEY_F6 = "F6"
Global Const $DLIB_IMAGE_WINDOW_KEY_F7 = "F7"
Global Const $DLIB_IMAGE_WINDOW_KEY_F8 = "F8"
Global Const $DLIB_IMAGE_WINDOW_KEY_F9 = "F9"
Global Const $DLIB_IMAGE_WINDOW_KEY_F10 = "F10"
Global Const $DLIB_IMAGE_WINDOW_KEY_F11 = "F11"
Global Const $DLIB_IMAGE_WINDOW_KEY_F12 = "F12"

; gender_t
Global Const $DLIB_IMAGE_DATASET_METADATA_UNKNOWN = 0
Global Const $DLIB_IMAGE_DATASET_METADATA_MALE = 1
Global Const $DLIB_IMAGE_DATASET_METADATA_FEMALE = 2
